name: Latest Blog Posts
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch:
jobs:
  update-readme-with-hashnode-blog:
    name: Update README with the latest Blog Posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://vineelsai.com/index.xml"
